apiVersion: apps/v1
kind: Deployment
metadata:
 name: looking-glass
 namespace: nixlabs
spec:
 replicas: 4
 selector:
   matchLabels:
     app: looking-glass
 template:
   metadata:
     labels:
       app: looking-glass
   spec:
     containers:
       - name: looking-glass
         image: ghcr.io/nixlabs-dev/looking-glass:3708214ba273819665d973ea496e555815c0914d
         ports:
           - name: web
             containerPort: 3000
         env: 
          - name: SSH_KEY
            valueFrom:
              secretKeyRef:
               name: looking-glass-environment
               key: SSH_KEY
     imagePullSecrets:
       - name: ghcr